//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activity_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activity_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _655956565 {
            get {
                object obj = ResourceManager.GetObject("655956565", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a_yellow_bmw_b7_xdrive_car_driving_down_a_city_street_nostalgic_photography_detailed_cinematic_pho_246202850 {
            get {
                object obj = ResourceManager.GetObject("a-yellow-bmw-b7-xdrive-car-driving-down-a-city-street-nostalgic-photography-detai" +
                        "led-cinematic-pho-246202850", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_taxi_in_a_street_of_kolkata_professional_ominous_concept_art_by_artgerm_and_greg_rutkowski__442265486 {
            get {
                object obj = ResourceManager.GetObject("blue-taxi-in-a-street-of-kolkata-professional-ominous-concept-art-by-artgerm-and-" +
                        "greg-rutkowski--442265486", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap colorfulgalaxy_universenebulaunreal_enginecinematic_lighting3d_cartoonhigh_detail_4k_8k_tr_247410794 {
            get {
                object obj = ResourceManager.GetObject("colorfulgalaxy-universenebulaunreal-enginecinematic-lighting3d-cartoonhigh-detail" +
                        "-4k-8k-tr-247410794", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creating_a_personal_driver_logo_uniqueness_and_individuality__attractiveness__good_readability__s_162686694 {
            get {
                object obj = ResourceManager.GetObject("creating-a-personal-driver-logo-uniqueness-and-individuality--attractiveness--goo" +
                        "d-readability--s-162686694", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creating_a_personal_driver_logo_uniqueness_and_individuality__attractiveness__good_readability__s_1626866941 {
            get {
                object obj = ResourceManager.GetObject("creating-a-personal-driver-logo-uniqueness-and-individuality--attractiveness--goo" +
                        "d-readability--s-1626866941", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20210616_14620_1hsw5s4 {
            get {
                object obj = ResourceManager.GetObject("image_processing20210616-14620-1hsw5s4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image_processing20210616_14620_1hsw5s41 {
            get {
                object obj = ResourceManager.GetObject("image_processing20210616-14620-1hsw5s41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Person_Icon_12 {
            get {
                object obj = ResourceManager.GetObject("Person Icon_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Person_Icon_121 {
            get {
                object obj = ResourceManager.GetObject("Person Icon_121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Person_Icon_122 {
            get {
                object obj = ResourceManager.GetObject("Person Icon_122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
